name: mongo-sharding-repl
services:
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://router"
      MONGODB_DATABASE_NAME: "somedb"

  shard1-r1:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: shard1-r1
    restart: always
    ports:
      - "27016:27016"
    volumes:
      - shard1-r1_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.14
    depends_on:
      - shard1
    command:
      [
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27016"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-r2:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: shard1-r2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - shard1-r2_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.13
    depends_on:
      - shard1
    command:
      [
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27017"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-r1:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: shard2-r1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard2-r1_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    depends_on:
      - shard2
    command:
      [
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27018"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-r2:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: shard2-r2
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-r2_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    depends_on:
      - shard2
    command:
      [
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27020:27020"
    volumes:
      - config-data:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27021:27021"
    volumes:
      - shard1-data:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27022:27022"
    volumes:
      - shard2-data:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    command:
      [
        "--shardsvr", #запуск в режиме
        "--replSet",
        "shard2", #название реплик
        "--bind_ip_all", #обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  router:
    image: mongo:latest
    container_name: router
    restart: always
    ports:
      - "27023:27023"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27020",
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  shard1-r1_data_container:
  shard1-r2_data_container:
  shard2-r1_data_container:
  shard2-r2_data_container:
  config-data:
  shard1-data:
  shard2-data: